# Generated by Django 3.2.3 on 2022-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIDM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagejsonmodel',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagejsonmodel',
            name='json',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
