# Generated by Django 3.2.3 on 2022-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIDM', '0002_auto_20220224_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejsonmodel',
            name='imagejson',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='imagejsonmodel',
            name='textjson',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
