# Generated by Django 3.2.3 on 2022-02-24 15:50

import UIDM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIDM', '0003_auto_20220224_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagejsonmodel',
            name='image',
            field=models.FileField(null=True, upload_to=UIDM.models.get_image_path),
        ),
    ]
