# Generated by Django 3.2.3 on 2022-02-26 14:28

import UIDM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIDM', '0005_auto_20220225_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagejsonmodel',
            name='detectedimage',
            field=models.FileField(null=True, upload_to=UIDM.models.get_detectedimage_path),
        ),
    ]
